# Auto-generated category mappings from Right Sector

FULLNAME_TO_CATEGORY = {
    'AXIS INNOVATION': 'BROAD',
    'DSP ELSS': 'BROAD',
    'DSP QUANT': 'BROAD',
    'HSBC BUSINESS CYCLES FUND - REGULAR GROWTH': 'BROAD',
    'ICICI PRU SILVER': 'BROAD',
    'KOTAK CONTRA': 'BROAD',
    'KOTAK GOLD': 'BROAD',
    'NIFTY 50 FUTURES TR INDEX': 'STRATEGY',
    'NIFTY 500 EQUAL WEIGHT': 'BROAD',
    'NIFTY 500 MULTICAP 50:25:25': 'BROAD',
    'NIFTY 500 MULTICAP MOMENTUM QUALITY 50': 'STRATEGY',
    'NIFTY ALPHA 50': 'STRATEGY',
    'NIFTY ALPHA QUALITY VALUE LOW VOLATILITY 30': 'STRATEGY',
    'NIFTY ALPHALOWVOL': 'STRATEGY',
    'NIFTY CAPITAL MARKETS': 'THEMATIC',
    'NIFTY CONSR DURBL': 'SECTOR',
    'NIFTY EV & NEW AGE AUTOMOTIVE': 'THEMATIC',
    'NIFTY FINSRV25 50': 'SECTOR',
    'NIFTY HEALTHCARE': 'SECTOR',
    'NIFTY IND DIGITAL': 'THEMATIC',
    'NIFTY INDIA DEFENCE': 'THEMATIC',
    'NIFTY INDIA INTERNET': 'THEMATIC',
    'NIFTY INDIA MFG': 'THEMATIC',
    'NIFTY INDIA RAILWAYS PSU': 'THEMATIC',
    'NIFTY INFRALOG': 'THEMATIC',
    'NIFTY IPO': 'THEMATIC',
    'NIFTY LARGEMID250': 'BROAD',
    'NIFTY M150 QLTY50': 'STRATEGY',
    'NIFTY MICROCAP250': 'BROAD',
    'NIFTY MID SELECT': 'BROAD',
    'NIFTY MIDCAP 100': 'BROAD',
    'NIFTY MIDCAP 150': 'BROAD',
    'NIFTY MIDSML 400': 'BROAD',
    'NIFTY MIDSML HLTH': 'SECTOR',
    'NIFTY MULTI INFRA': 'THEMATIC',
    'NIFTY MULTI MFG': 'THEMATIC',
    'NIFTY OIL AND GAS': 'SECTOR',
    'NIFTY REITS & INVITS': 'THEMATIC',
    'NIFTY SME EMERGE': 'THEMATIC',
    'NIFTY SMLCAP 100': 'BROAD',
    'NIFTY SMLCAP 250': 'BROAD',
    'NIFTY SMLCAP 50': 'BROAD',
    'NIFTY TATA 25 CAP': 'THEMATIC',
    'NIFTY TMMQ 50': 'STRATEGY',
    'NIFTY TOTAL MKT': 'BROAD',
    'NIFTY100 EQL WGT': 'STRATEGY',
    'NIFTY100 ESG': 'THEMATIC',
    'NIFTY100 LOWVOL30': 'STRATEGY',
    'NIFTY100 QUALTY30': 'STRATEGY',
    'NIFTY200 QUALITY 30': 'STRATEGY',
    'NIFTY50 EQL WGT': 'STRATEGY',
    'NIFTY500 FLEXICAP': 'STRATEGY',
    'NIFTY500 HEALTH': 'SECTOR',
    'NIFTY500 MULTICAP': 'BROAD',
    'NIFTYM150MOMNTM50': 'STRATEGY',
    'Nifty 100': 'BROAD',
    'Nifty 200': 'BROAD',
    'Nifty 50': 'BROAD',
    'Nifty 500': 'BROAD',
    'Nifty AQL 30': 'STRATEGY',
    'Nifty AQLV 30': 'STRATEGY',
    'Nifty Auto': 'SECTOR',
    'Nifty Bank': 'SECTOR',
    'Nifty CPSE': 'THEMATIC',
    'Nifty Chemicals': 'SECTOR',
    'Nifty Commodities': 'THEMATIC',
    'Nifty Conglomerate 50': 'THEMATIC',
    'Nifty Consumption': 'THEMATIC',
    'Nifty CoreHousing': 'THEMATIC',
    'Nifty Corp MAATR': 'THEMATIC',
    'Nifty Div Opps 50': 'STRATEGY',
    'Nifty Energy': 'THEMATIC',
    'Nifty FMCG': 'SECTOR',
    'Nifty Fin Service': 'SECTOR',
    'Nifty FinSerExBnk': 'SECTOR',
    'Nifty GS 10Yr Cln': 'STRATEGY',
    'Nifty GrowSect 15': 'STRATEGY',
    'Nifty HighBeta 50': 'STRATEGY',
    'Nifty Housing': 'THEMATIC',
    'Nifty IT': 'SECTOR',
    'Nifty Ind Tourism': 'THEMATIC',
    'Nifty India Corporate Group Index - Aditya Birla Group': 'THEMATIC',
    'Nifty India Corporate Group Index - Mahindra Group': 'THEMATIC',
    'Nifty India Corporate Group Index - Tata Group': 'THEMATIC',
    'Nifty Infra': 'THEMATIC',
    'Nifty Low Vol 50': 'STRATEGY',
    'Nifty MNC': 'THEMATIC',
    'Nifty MS Fin Serv': 'SECTOR',
    'Nifty MS IT Telcm': 'SECTOR',
    'Nifty MS Ind Cons': 'THEMATIC',
    'Nifty Media': 'SECTOR',
    'Nifty Metal': 'SECTOR',
    'Nifty Mid Liq 15': 'THEMATIC',
    'Nifty Midcap 50': 'BROAD',
    'Nifty Mobility': 'THEMATIC',
    'Nifty Multi MQ 50': 'STRATEGY',
    'Nifty New Consump': 'THEMATIC',
    'Nifty Next 50': 'BROAD',
    'Nifty NonCyc Cons': 'THEMATIC',
    'Nifty PSE': 'THEMATIC',
    'Nifty PSU Bank': 'SECTOR',
    'Nifty Pharma': 'SECTOR',
    'Nifty Pvt Bank': 'SECTOR',
    'Nifty Qlty LV 30': 'STRATEGY',
    'Nifty Realty': 'SECTOR',
    'Nifty Rural': 'THEMATIC',
    'Nifty Serv Sector': 'THEMATIC',
    'Nifty Shariah 25': 'THEMATIC',
    'Nifty Sml250 Q50': 'STRATEGY',
    'Nifty Top 10 EW': 'STRATEGY',
    'Nifty Top 15 EW': 'STRATEGY',
    'Nifty Top 20 EW': 'STRATEGY',
    'Nifty Trans Logis': 'THEMATIC',
    'Nifty Waves': 'THEMATIC',
    'Nifty100 Alpha 30': 'STRATEGY',
    'Nifty100 Enh ESG': 'THEMATIC',
    'Nifty100 Liq 15': 'THEMATIC',
    'Nifty100ESGSecLdr': 'THEMATIC',
    'Nifty200 Alpha 30': 'STRATEGY',
    'Nifty200 Value 30': 'STRATEGY',
    'Nifty200Momentm30': 'STRATEGY',
    'Nifty50 Shariah': 'THEMATIC',
    'Nifty50 Value 20': 'STRATEGY',
    'Nifty500 EW': 'STRATEGY',
    'Nifty500 LMS Eql': 'STRATEGY',
    'Nifty500 LowVol50': 'STRATEGY',
    'Nifty500 MQVLv50': 'STRATEGY',
    'Nifty500 Qlty50': 'STRATEGY',
    'Nifty500 Shariah': 'THEMATIC',
    'Nifty500 Value 50': 'STRATEGY',
    'Nifty500Momentm50': 'STRATEGY',
    'NiftyMS400 MQ 100': 'STRATEGY',
    'NiftySml250MQ 100': 'STRATEGY',
    'UTI FLEX': 'BROAD',
}

FULLNAME_TO_SHORTNAME = {
    'AXIS INNOVATION': 'NINNOV',
    'DSP ELSS': 'NELSS',
    'DSP QUANT': 'NQUANT',
    'HSBC BUSINESS CYCLES FUND - REGULAR GROWTH': 'NHSBCYCLE',
    'ICICI PRU SILVER': 'NSILVER',
    'KOTAK CONTRA': 'NCONTRA',
    'KOTAK GOLD': 'NGOLD',
    'NIFTY 50 FUTURES TR INDEX': 'N50FTR',
    'NIFTY 500 EQUAL WEIGHT': 'N500EQ',
    'NIFTY 500 MULTICAP 50:25:25': 'NMC5025',
    'NIFTY 500 MULTICAP MOMENTUM QUALITY 50': 'N5MCMQ5',
    'NIFTY ALPHA 50': 'NAL50',
    'NIFTY ALPHA QUALITY VALUE LOW VOLATILITY 30': 'NAQVLV30',
    'NIFTY ALPHALOWVOL': 'NALV30',
    'NIFTY CAPITAL MARKETS': 'NCM',
    'NIFTY CONSR DURBL': 'NCONDUR',
    'NIFTY EV & NEW AGE AUTOMOTIVE': 'NEVNAA',
    'NIFTY FINSRV25 50': 'NFINS25',
    'NIFTY HEALTHCARE': 'NHEALTH',
    'NIFTY IND DIGITAL': 'NIDIGI',
    'NIFTY INDIA DEFENCE': 'NIDEF',
    'NIFTY INDIA INTERNET': 'NIINT',
    'NIFTY INDIA MFG': 'NIMFG',
    'NIFTY INDIA RAILWAYS PSU': 'NRPSU',
    'NIFTY INFRALOG': 'NIFSL',
    'NIFTY IPO': 'NIPO',
    'NIFTY LARGEMID250': 'NLMC250',
    'NIFTY M150 QLTY50': 'NMC150Q',
    'NIFTY MICROCAP250': 'NMICRO',
    'NIFTY MID SELECT': 'NMIDSEL',
    'NIFTY MIDCAP 100': 'NMC100',
    'NIFTY MIDCAP 150': 'NMC150',
    'NIFTY MIDSML 400': 'NMSC400',
    'NIFTY MIDSML HLTH': 'NMSHC',
    'NIFTY MULTI INFRA': 'NINFRA532',
    'NIFTY MULTI MFG': 'NMFG532',
    'NIFTY OIL AND GAS': 'NOILGAS',
    'NIFTY REITS & INVITS': 'NREiT',
    'NIFTY SME EMERGE': 'NSMEE',
    'NIFTY SMLCAP 100': 'NSC100',
    'NIFTY SMLCAP 250': 'NSC250',
    'NIFTY SMLCAP 50': 'NSC50',
    'NIFTY TATA 25 CAP': 'NTATA25C',
    'NIFTY TMMQ 50': 'NTMF50',
    'NIFTY TOTAL MKT': 'NTOTLM',
    'NIFTY100 EQL WGT': 'N100EQWT',
    'NIFTY100 ESG': 'N100ESG',
    'NIFTY100 LOWVOL30': 'N100LV30',
    'NIFTY100 QUALTY30': 'N100QLT30',
    'NIFTY200 QUALITY 30': 'N200Q30',
    'NIFTY50 EQL WGT': 'N50EQWGT',
    'NIFTY500 FLEXICAP': 'N5FCQ3',
    'NIFTY500 HEALTH': 'N500HLTH',
    'NIFTY500 MULTICAP': 'N500',
    'NIFTYM150MOMNTM50': 'NM150M50',
    'Nifty 100': 'N100',
    'Nifty 200': 'N200',
    'Nifty 50': 'N50',
    'Nifty 500': 'N500',
    'Nifty AQL 30': 'NAQLV30',
    'Nifty AQLV 30': 'NAQLV30',
    'Nifty Auto': 'NAUTO',
    'Nifty Bank': 'NBANK',
    'Nifty CPSE': 'NCPSE',
    'Nifty Chemicals': 'NCHEM',
    'Nifty Commodities': 'NCOMM',
    'Nifty Conglomerate 50': 'NCONG50',
    'Nifty Consumption': 'NICON',
    'Nifty CoreHousing': 'NCHOUS',
    'Nifty Corp MAATR': 'NMAATR',
    'Nifty Div Opps 50': 'NDIVOP50',
    'Nifty Energy': 'NENERGY',
    'Nifty FMCG': 'NFMCG',
    'Nifty Fin Service': 'NFINSERV',
    'Nifty FinSerExBnk': 'NFINSEXB',
    'Nifty GS 10Yr Cln': 'N5ARB',
    'Nifty GrowSect 15': 'NGROW15',
    'Nifty HighBeta 50': 'NHBETA50',
    'Nifty Housing': 'NHOUSING',
    'Nifty IT': 'NTECH',
    'Nifty Ind Tourism': 'NTOUR',
    'Nifty India Corporate Group Index - Aditya Birla Group': 'NBIRLA',
    'Nifty India Corporate Group Index - Mahindra Group': 'NMAHIN',
    'Nifty India Corporate Group Index - Tata Group': 'NTATA',
    'Nifty Infra': 'NINFRA',
    'Nifty Low Vol 50': 'NLV50',
    'Nifty MNC': 'NMNC',
    'Nifty MS Fin Serv': 'NMSFINS',
    'Nifty MS IT Telcm': 'NMSITT',
    'Nifty MS Ind Cons': 'NMSICON',
    'Nifty Media': 'NMEDIA',
    'Nifty Metal': 'NMETAL',
    'Nifty Mid Liq 15': 'NMIDLIQ15',
    'Nifty Midcap 50': 'NMC50',
    'Nifty Mobility': 'NMOBIL',
    'Nifty Multi MQ 50': 'NMQLV',
    'Nifty New Consump': 'NNACON',
    'Nifty Next 50': 'NN50',
    'Nifty NonCyc Cons': 'NNCCON',
    'Nifty PSE': 'NPSE',
    'Nifty PSU Bank': 'NPSUBANK',
    'Nifty Pharma': 'NPHARMA',
    'Nifty Pvt Bank': 'NPVTBANK',
    'Nifty Qlty LV 30': 'NQLV30',
    'Nifty Realty': 'NREALTY',
    'Nifty Rural': 'NRRL',
    'Nifty Serv Sector': 'NSERVSEC',
    'Nifty Shariah 25': 'NSH25',
    'Nifty Sml250 Q50': 'NSC250Q',
    'Nifty Top 10 EW': 'NT10EQWT',
    'Nifty Top 15 EW': 'NT15EW',
    'Nifty Top 20 EW': 'NT20EW',
    'Nifty Trans Logis': 'NTRANS',
    'Nifty Waves': 'NWVS',
    'Nifty100 Alpha 30': 'N100AL30',
    'Nifty100 Enh ESG': 'N100ESGE',
    'Nifty100 Liq 15': 'NLCLIQ15',
    'Nifty100ESGSecLdr': 'N100ESGSL',
    'Nifty200 Alpha 30': 'N200AL30',
    'Nifty200 Value 30': 'N200V30',
    'Nifty200Momentm30': 'N200M30',
    'Nifty50 Shariah': 'N50SH',
    'Nifty50 Value 20': 'N50V20',
    'Nifty500 EW': 'N500EQWT',
    'Nifty500 LMS Eql': 'N500LMS',
    'Nifty500 LowVol50': 'N5LV5',
    'Nifty500 MQVLv50': 'NMQLV',
    'Nifty500 Qlty50': 'N500QLT50',
    'Nifty500 Shariah': 'N500SH',
    'Nifty500 Value 50': 'N500V50',
    'Nifty500Momentm50': 'N500M50',
    'NiftyMS400 MQ 100': 'NMSCMQ',
    'NiftySml250MQ 100': 'NSC250MQ',
    'UTI FLEX': 'NFLEXI',
}

SHORTNAME_TO_FULLNAME = {
    'N100': 'Nifty 100',
    'N100AL30': 'Nifty100 Alpha 30',
    'N100EQWT': 'NIFTY100 EQL WGT',
    'N100ESG': 'NIFTY100 ESG',
    'N100ESGE': 'Nifty100 Enh ESG',
    'N100ESGSL': 'Nifty100ESGSecLdr',
    'N100LV30': 'NIFTY100 LOWVOL30',
    'N100QLT30': 'NIFTY100 QUALTY30',
    'N200': 'Nifty 200',
    'N200AL30': 'Nifty200 Alpha 30',
    'N200M30': 'Nifty200Momentm30',
    'N200Q30': 'NIFTY200 QUALITY 30',
    'N200V30': 'Nifty200 Value 30',
    'N50': 'Nifty 50',
    'N500': 'NIFTY500 MULTICAP',
    'N500EQ': 'NIFTY 500 EQUAL WEIGHT',
    'N500EQWT': 'Nifty500 EW',
    'N500HLTH': 'NIFTY500 HEALTH',
    'N500LMS': 'Nifty500 LMS Eql',
    'N500M50': 'Nifty500Momentm50',
    'N500QLT50': 'Nifty500 Qlty50',
    'N500SH': 'Nifty500 Shariah',
    'N500V50': 'Nifty500 Value 50',
    'N50EQWGT': 'NIFTY50 EQL WGT',
    'N50FTR': 'NIFTY 50 FUTURES TR INDEX',
    'N50SH': 'Nifty50 Shariah',
    'N50V20': 'Nifty50 Value 20',
    'N5ARB': 'Nifty GS 10Yr Cln',
    'N5FCQ3': 'NIFTY500 FLEXICAP',
    'N5LV5': 'Nifty500 LowVol50',
    'N5MCMQ5': 'NIFTY 500 MULTICAP MOMENTUM QUALITY 50',
    'NAL50': 'NIFTY ALPHA 50',
    'NALV30': 'NIFTY ALPHALOWVOL',
    'NAQLV30': 'Nifty AQLV 30',
    'NAQVLV30': 'NIFTY ALPHA QUALITY VALUE LOW VOLATILITY 30',
    'NAUTO': 'Nifty Auto',
    'NBANK': 'Nifty Bank',
    'NBIRLA': 'Nifty India Corporate Group Index - Aditya Birla Group',
    'NCHEM': 'Nifty Chemicals',
    'NCHOUS': 'Nifty CoreHousing',
    'NCM': 'NIFTY CAPITAL MARKETS',
    'NCOMM': 'Nifty Commodities',
    'NCONDUR': 'NIFTY CONSR DURBL',
    'NCONG50': 'Nifty Conglomerate 50',
    'NCONTRA': 'KOTAK CONTRA',
    'NCPSE': 'Nifty CPSE',
    'NDIVOP50': 'Nifty Div Opps 50',
    'NELSS': 'DSP ELSS',
    'NENERGY': 'Nifty Energy',
    'NEVNAA': 'NIFTY EV & NEW AGE AUTOMOTIVE',
    'NFINS25': 'NIFTY FINSRV25 50',
    'NFINSERV': 'Nifty Fin Service',
    'NFINSEXB': 'Nifty FinSerExBnk',
    'NFLEXI': 'UTI FLEX',
    'NFMCG': 'Nifty FMCG',
    'NGOLD': 'KOTAK GOLD',
    'NGROW15': 'Nifty GrowSect 15',
    'NHBETA50': 'Nifty HighBeta 50',
    'NHEALTH': 'NIFTY HEALTHCARE',
    'NHOUSING': 'Nifty Housing',
    'NHSBCYCLE': 'HSBC BUSINESS CYCLES FUND - REGULAR GROWTH',
    'NICON': 'Nifty Consumption',
    'NIDEF': 'NIFTY INDIA DEFENCE',
    'NIDIGI': 'NIFTY IND DIGITAL',
    'NIFSL': 'NIFTY INFRALOG',
    'NIINT': 'NIFTY INDIA INTERNET',
    'NIMFG': 'NIFTY INDIA MFG',
    'NINFRA': 'Nifty Infra',
    'NINFRA532': 'NIFTY MULTI INFRA',
    'NINNOV': 'AXIS INNOVATION',
    'NIPO': 'NIFTY IPO',
    'NLCLIQ15': 'Nifty100 Liq 15',
    'NLMC250': 'NIFTY LARGEMID250',
    'NLV50': 'Nifty Low Vol 50',
    'NM150M50': 'NIFTYM150MOMNTM50',
    'NMAATR': 'Nifty Corp MAATR',
    'NMAHIN': 'Nifty India Corporate Group Index - Mahindra Group',
    'NMC100': 'NIFTY MIDCAP 100',
    'NMC150': 'NIFTY MIDCAP 150',
    'NMC150Q': 'NIFTY M150 QLTY50',
    'NMC50': 'Nifty Midcap 50',
    'NMC5025': 'NIFTY 500 MULTICAP 50:25:25',
    'NMEDIA': 'Nifty Media',
    'NMETAL': 'Nifty Metal',
    'NMFG532': 'NIFTY MULTI MFG',
    'NMICRO': 'NIFTY MICROCAP250',
    'NMIDLIQ15': 'Nifty Mid Liq 15',
    'NMIDSEL': 'NIFTY MID SELECT',
    'NMNC': 'Nifty MNC',
    'NMOBIL': 'Nifty Mobility',
    'NMQLV': 'Nifty500 MQVLv50',
    'NMSC400': 'NIFTY MIDSML 400',
    'NMSCMQ': 'NiftyMS400 MQ 100',
    'NMSFINS': 'Nifty MS Fin Serv',
    'NMSHC': 'NIFTY MIDSML HLTH',
    'NMSICON': 'Nifty MS Ind Cons',
    'NMSITT': 'Nifty MS IT Telcm',
    'NN50': 'Nifty Next 50',
    'NNACON': 'Nifty New Consump',
    'NNCCON': 'Nifty NonCyc Cons',
    'NOILGAS': 'NIFTY OIL AND GAS',
    'NPHARMA': 'Nifty Pharma',
    'NPSE': 'Nifty PSE',
    'NPSUBANK': 'Nifty PSU Bank',
    'NPVTBANK': 'Nifty Pvt Bank',
    'NQLV30': 'Nifty Qlty LV 30',
    'NQUANT': 'DSP QUANT',
    'NREALTY': 'Nifty Realty',
    'NREiT': 'NIFTY REITS & INVITS',
    'NRPSU': 'NIFTY INDIA RAILWAYS PSU',
    'NRRL': 'Nifty Rural',
    'NSC100': 'NIFTY SMLCAP 100',
    'NSC250': 'NIFTY SMLCAP 250',
    'NSC250MQ': 'NiftySml250MQ 100',
    'NSC250Q': 'Nifty Sml250 Q50',
    'NSC50': 'NIFTY SMLCAP 50',
    'NSERVSEC': 'Nifty Serv Sector',
    'NSH25': 'Nifty Shariah 25',
    'NSILVER': 'ICICI PRU SILVER',
    'NSMEE': 'NIFTY SME EMERGE',
    'NT10EQWT': 'Nifty Top 10 EW',
    'NT15EW': 'Nifty Top 15 EW',
    'NT20EW': 'Nifty Top 20 EW',
    'NTATA': 'Nifty India Corporate Group Index - Tata Group',
    'NTATA25C': 'NIFTY TATA 25 CAP',
    'NTECH': 'Nifty IT',
    'NTMF50': 'NIFTY TMMQ 50',
    'NTOTLM': 'NIFTY TOTAL MKT',
    'NTOUR': 'Nifty Ind Tourism',
    'NTRANS': 'Nifty Trans Logis',
    'NWVS': 'Nifty Waves',
}

SHORTNAME_TO_CATEGORY = {
    'N100': 'BROAD',
    'N100AL30': 'STRATEGY',
    'N100EQWT': 'STRATEGY',
    'N100ESG': 'THEMATIC',
    'N100ESGE': 'THEMATIC',
    'N100ESGSL': 'THEMATIC',
    'N100LV30': 'STRATEGY',
    'N100QLT30': 'STRATEGY',
    'N200': 'BROAD',
    'N200AL30': 'STRATEGY',
    'N200M30': 'STRATEGY',
    'N200Q30': 'STRATEGY',
    'N200V30': 'STRATEGY',
    'N50': 'BROAD',
    'N500': 'BROAD',
    'N500EQ': 'BROAD',
    'N500EQWT': 'STRATEGY',
    'N500HLTH': 'SECTOR',
    'N500LMS': 'STRATEGY',
    'N500M50': 'STRATEGY',
    'N500QLT50': 'STRATEGY',
    'N500SH': 'THEMATIC',
    'N500V50': 'STRATEGY',
    'N50EQWGT': 'STRATEGY',
    'N50FTR': 'STRATEGY',
    'N50SH': 'THEMATIC',
    'N50V20': 'STRATEGY',
    'N5ARB': 'STRATEGY',
    'N5FCQ3': 'STRATEGY',
    'N5LV5': 'STRATEGY',
    'N5MCMQ5': 'STRATEGY',
    'NAL50': 'STRATEGY',
    'NALV30': 'STRATEGY',
    'NAQLV30': 'STRATEGY',
    'NAQVLV30': 'STRATEGY',
    'NAUTO': 'SECTOR',
    'NBANK': 'SECTOR',
    'NBIRLA': 'THEMATIC',
    'NCHEM': 'SECTOR',
    'NCHOUS': 'THEMATIC',
    'NCM': 'THEMATIC',
    'NCOMM': 'THEMATIC',
    'NCONDUR': 'SECTOR',
    'NCONG50': 'THEMATIC',
    'NCONTRA': 'BROAD',
    'NCPSE': 'THEMATIC',
    'NDIVOP50': 'STRATEGY',
    'NELSS': 'BROAD',
    'NENERGY': 'THEMATIC',
    'NEVNAA': 'THEMATIC',
    'NFINS25': 'SECTOR',
    'NFINSERV': 'SECTOR',
    'NFINSEXB': 'SECTOR',
    'NFLEXI': 'BROAD',
    'NFMCG': 'SECTOR',
    'NGOLD': 'BROAD',
    'NGROW15': 'STRATEGY',
    'NHBETA50': 'STRATEGY',
    'NHEALTH': 'SECTOR',
    'NHOUSING': 'THEMATIC',
    'NHSBCYCLE': 'BROAD',
    'NICON': 'THEMATIC',
    'NIDEF': 'THEMATIC',
    'NIDIGI': 'THEMATIC',
    'NIFSL': 'THEMATIC',
    'NIINT': 'THEMATIC',
    'NIMFG': 'THEMATIC',
    'NINFRA': 'THEMATIC',
    'NINFRA532': 'THEMATIC',
    'NINNOV': 'BROAD',
    'NIPO': 'THEMATIC',
    'NLCLIQ15': 'THEMATIC',
    'NLMC250': 'BROAD',
    'NLV50': 'STRATEGY',
    'NM150M50': 'STRATEGY',
    'NMAATR': 'THEMATIC',
    'NMAHIN': 'THEMATIC',
    'NMC100': 'BROAD',
    'NMC150': 'BROAD',
    'NMC150Q': 'STRATEGY',
    'NMC50': 'BROAD',
    'NMC5025': 'BROAD',
    'NMEDIA': 'SECTOR',
    'NMETAL': 'SECTOR',
    'NMFG532': 'THEMATIC',
    'NMICRO': 'BROAD',
    'NMIDLIQ15': 'THEMATIC',
    'NMIDSEL': 'BROAD',
    'NMNC': 'THEMATIC',
    'NMOBIL': 'THEMATIC',
    'NMQLV': 'STRATEGY',
    'NMSC400': 'BROAD',
    'NMSCMQ': 'STRATEGY',
    'NMSFINS': 'SECTOR',
    'NMSHC': 'SECTOR',
    'NMSICON': 'THEMATIC',
    'NMSITT': 'SECTOR',
    'NN50': 'BROAD',
    'NNACON': 'THEMATIC',
    'NNCCON': 'THEMATIC',
    'NOILGAS': 'SECTOR',
    'NPHARMA': 'SECTOR',
    'NPSE': 'THEMATIC',
    'NPSUBANK': 'SECTOR',
    'NPVTBANK': 'SECTOR',
    'NQLV30': 'STRATEGY',
    'NQUANT': 'BROAD',
    'NREALTY': 'SECTOR',
    'NREiT': 'THEMATIC',
    'NRPSU': 'THEMATIC',
    'NRRL': 'THEMATIC',
    'NSC100': 'BROAD',
    'NSC250': 'BROAD',
    'NSC250MQ': 'STRATEGY',
    'NSC250Q': 'STRATEGY',
    'NSC50': 'BROAD',
    'NSERVSEC': 'THEMATIC',
    'NSH25': 'THEMATIC',
    'NSILVER': 'BROAD',
    'NSMEE': 'THEMATIC',
    'NT10EQWT': 'STRATEGY',
    'NT15EW': 'STRATEGY',
    'NT20EW': 'STRATEGY',
    'NTATA': 'THEMATIC',
    'NTATA25C': 'THEMATIC',
    'NTECH': 'SECTOR',
    'NTMF50': 'STRATEGY',
    'NTOTLM': 'BROAD',
    'NTOUR': 'THEMATIC',
    'NTRANS': 'THEMATIC',
    'NWVS': 'THEMATIC',
}
